name: cicd

on:
  push: 
    branches: [ "main" ]  
  pull_request:
    branches: [ "main" ] 
  workflow_dispatch:


jobs:
  init_build: 
    runs-on: ubuntu-latest 
    env:
      ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
      SERVER_HOSTNAME: ${{ secrets.SERVER_HOSTNAME }}
    steps: 
       
      - uses: actions/checkout@v2 
      - name: Set up Python 3.8
        uses: actions/setup-python@v1
        with:
          python-version: 3.8
      - name: Install dependencies
        run: make install

      - name: Lint 
        run: make lint
      - name: extract 
        run: make extract 
      - name: transform_load
        run: make transform_load 
      - name: query
        run: make query
      - name: Format
        run: make format

      - name: Test
        run: make test
